# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
xcode_scheme: ZHTabBarController-Example
xcode_sdk: iphonesimulator10.0

podfile: Example/Podfile

before_install:
- gem install cocoapods
- pod install --project-directory=Example

script:
- echo Check if the library described by the podspec can be built
- pod lib lint --allow-warnings

- echo Build the Demo apps and run tests
- xcodebuild -workspace Example/ZHTabBarController.xcworkspace -scheme ZHTabBarController-Example -destination name="iPhone 6" build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_success:
- bash <(curl -s https://codecov.io/bash)